"""store_id 외래키 CASCADE로 변경

Revision ID: 23be1c38ecbe
Revises: fc5f7c21e808
Create Date: 2025-05-23 00:41:01.236028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23be1c38ecbe'
down_revision: Union[str, None] = 'fc5f7c21e808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('contents_ibfk_7', 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'stores', ['store_id'], ['store_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key('contents_ibfk_7', 'contents', 'stores', ['store_id'], ['store_id'])

    # ### end Alembic commands ###
