"""sync with current models

Revision ID: 2a27ad2ce12e
Revises: 
Create Date: 2025-04-19 00:35:40.297899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a27ad2ce12e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_kakao_id'), 'accounts', ['kakao_id'], unique=True)
    op.drop_column('accounts', 'is_deleted')
    op.drop_constraint('FK_CONTENTS_GENDER', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_AGE', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_PLATFORMS', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_FORMATS', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_USERS', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_EXTERNAL', 'contents', type_='foreignkey')
    op.drop_constraint('FK_CONTENTS_ITEMS', 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'items', ['item_id'], ['item_id'])
    op.create_foreign_key(None, 'contents', 'ages', ['age_id'], ['age_id'])
    op.create_foreign_key(None, 'contents', 'genders', ['gender_id'], ['gender_id'])
    op.create_foreign_key(None, 'contents', 'external_data', ['external_data_id'], ['external_data_id'])
    op.create_foreign_key(None, 'contents', 'formats', ['format_id'], ['format_id'])
    op.create_foreign_key(None, 'contents', 'platforms', ['platform_id'], ['platform_id'])
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key('FK_CONTENTS_ITEMS', 'contents', 'items', ['item_id'], ['item_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_EXTERNAL', 'contents', 'external_data', ['external_data_id'], ['external_data_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_USERS', 'contents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('FK_CONTENTS_FORMATS', 'contents', 'formats', ['format_id'], ['format_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_PLATFORMS', 'contents', 'platforms', ['platform_id'], ['platform_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_AGE', 'contents', 'ages', ['age_id'], ['age_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_GENDER', 'contents', 'genders', ['gender_id'], ['gender_id'], ondelete='SET NULL')
    op.add_column('accounts', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_accounts_kakao_id'), table_name='accounts')
    # ### end Alembic commands ###
