"""initial clean schema

Revision ID: 46661b9b5630
Revises: 
Create Date: 2025-04-17 05:22:00.548773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46661b9b5630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_foreign_key(None, 'contents', 'platforms', ['platform_id'], ['platform_id'])
    op.create_foreign_key(None, 'contents', 'external_data', ['external_data_id'], ['external_data_id'])
    op.create_foreign_key(None, 'contents', 'genders', ['gender_id'], ['gender_id'])
    op.create_foreign_key(None, 'contents', 'ages', ['age_id'], ['age_id'])
    op.create_foreign_key(None, 'contents', 'items', ['item_id'], ['item_id'])
    op.create_foreign_key(None, 'contents', 'formats', ['format_id'], ['format_id'])
    op.drop_column('contents', 'feedback')
    op.drop_column('contents', 'is_liked')
    op.drop_column('contents', 'guide_image')
    op.drop_column('contents', 'request')
    op.drop_column('contents', 'result_image')
    op.drop_column('contents', 'text_and_hashtag')
    op.alter_column('external_data', 'external_data_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('external_data', 'is_deleted')
    op.alter_column('formats', 'format_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('formats', 'is_deleted')
    op.alter_column('genders', 'gender_category',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('items', 'item_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('items', 'is_deleted')
    op.add_column('stores', sa.Column('store_address', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('store_category', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('store_phone', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('store_description', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.drop_column('stores', 'store_location')
    op.drop_column('stores', 'store_phone_number')
    op.alter_column('users', 'profile_image',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=2048),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.add_column('stores', sa.Column('store_phone_number', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('stores', sa.Column('store_location', mysql.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_column('stores', 'store_description')
    op.drop_column('stores', 'store_phone')
    op.drop_column('stores', 'store_category')
    op.drop_column('stores', 'store_address')
    op.add_column('items', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('items', 'item_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('genders', 'gender_category',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('formats', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('formats', 'format_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('external_data', sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('external_data', 'external_data_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('contents', sa.Column('text_and_hashtag', mysql.TEXT(), nullable=True))
    op.add_column('contents', sa.Column('result_image', mysql.TEXT(), nullable=True))
    op.add_column('contents', sa.Column('request', mysql.TEXT(), nullable=True))
    op.add_column('contents', sa.Column('guide_image', mysql.TEXT(), nullable=True))
    op.add_column('contents', sa.Column('is_liked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('contents', sa.Column('feedback', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key('FK_CONTENTS_ITEMS', 'contents', 'items', ['item_id'], ['item_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_FORMATS', 'contents', 'formats', ['format_id'], ['format_id'], ondelete='SET NULL')
    op.create_foreign_key('FK_CONTENTS_USERS', 'contents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('FK_CONTENTS_PLATFORMS', 'contents', 'platforms', ['platform_id'], ['platform_id'], ondelete='SET NULL')
    op.create_index('FK_CONTENTS_GENDER', 'contents', ['gender_id'], unique=False)
    op.create_index('FK_CONTENTS_EXTERNAL', 'contents', ['external_data_id'], unique=False)
    op.create_index('FK_CONTENTS_AGE', 'contents', ['age_id'], unique=False)
    op.alter_column('contents', 'external_data_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.drop_column('contents', 'user_image_url')
    # ### end Alembic commands ###
