"""add store_id in contents table

Revision ID: 5918adf11c6e
Revises: b4f8477dfd25
Create Date: 2025-05-12 13:02:59.209232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5918adf11c6e'
down_revision: Union[str, None] = 'b4f8477dfd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('contents', sa.Column('store_id', sa.BigInteger(), nullable=True))

    op.create_foreign_key(None, 'contents', 'stores', ['store_id'], ['store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')

    op.drop_column('contents', 'store_id')
    # ### end Alembic commands ###
