"""create external_data table

Revision ID: b4f8477dfd25
Revises: 7805610931b5
Create Date: 2025-05-07 22:43:18.816602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f8477dfd25'
down_revision: Union[str, None] = '7805610931b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.drop_index('FK_CONTENTS_AGE', table_name='contents')
    op.drop_index('FK_CONTENTS_EXTERNAL', table_name='contents')
    op.drop_index('FK_CONTENTS_FORMATS', table_name='contents')
    op.drop_index('FK_CONTENTS_GENDER', table_name='contents')
    op.drop_index('FK_CONTENTS_ITEMS', table_name='contents')
    op.drop_index('FK_CONTENTS_PLATFORMS', table_name='contents')
    op.drop_index('FK_CONTENTS_USERS', table_name='contents')
    '''
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('FK_CONTENTS_USERS', 'contents', ['user_id'], unique=False)
    op.create_index('FK_CONTENTS_PLATFORMS', 'contents', ['platform_id'], unique=False)
    op.create_index('FK_CONTENTS_ITEMS', 'contents', ['item_id'], unique=False)
    op.create_index('FK_CONTENTS_GENDER', 'contents', ['gender_id'], unique=False)
    op.create_index('FK_CONTENTS_FORMATS', 'contents', ['format_id'], unique=False)
    op.create_index('FK_CONTENTS_EXTERNAL', 'contents', ['external_data_id'], unique=False)
    op.create_index('FK_CONTENTS_AGE', 'contents', ['age_id'], unique=False)
    # ### end Alembic commands ###
