"""add promotion_name to content

Revision ID: e067b897a5a6
Revises: d0861cd85844
Create Date: 2025-05-16 23:42:04.674125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e067b897a5a6'
down_revision: Union[str, None] = 'd0861cd85844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('promotion_name', sa.String(length=50), nullable=True))
    op.drop_column('contents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('contents', 'promotion_name')
    # ### end Alembic commands ###
