"""add is_downloaded, is_shared, is_copied, increase request_text, result_hashtag, result_text

Revision ID: e6f2834fb450
Revises: e067b897a5a6
Create Date: 2025-05-17 00:14:08.523484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6f2834fb450'
down_revision: Union[str, None] = 'e067b897a5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('is_downloaded', sa.Boolean(), nullable=True))
    op.add_column('contents', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.add_column('contents', sa.Column('is_copied', sa.Boolean(), nullable=True))
    op.alter_column('contents', 'request_text',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('contents', 'result_text',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=3000),
               existing_nullable=True)
    op.alter_column('contents', 'result_hashtag',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('contents', 'promotion_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('contents', 'promotion_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contents', 'result_hashtag',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('contents', 'result_text',
               existing_type=sa.String(length=3000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('contents', 'request_text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('contents', 'is_copied')
    op.drop_column('contents', 'is_shared')
    op.drop_column('contents', 'is_downloaded')
    # ### end Alembic commands ###
